[package]
name = "lean4_rs"
version = "0.1.0"
edition = "2021"


[dependencies]
lean4_sys = { path = "lean4_sys" }
lean4_macro = { path = "lean4_macro" }

[workspace]
members = [
    "lean4_macro",
    "lean4_sys",
]